s1 = {"charan","baru","raju"}
print(s1)
s2 ={"baru","anitha","akash"}
print(s2)
s1.remove("charan")
print(s1)
s1.add("sriya")
print(s1)
s3 = s1.intersection(s2)
print(s3)
print(s1.union(s2))
s1.add("charan")
print(s1)
print(len(s1))
s1.discard("charan")
print(s1)
y = s1.isdisjoint(s2)
print(y)
z = s1.issubset(s2)
print(z)
c = s1.difference(s2)
print(s1)